---
title: "Non-pharmaceutical interventions for respiratory pandemics: challenges and potential solutions"
output: pdf_document
---


NPIs essential early in pandemic to buy time for treatment. For some pathogens, vaccines may not be as effective as needed, especially for engineered pathogens (or multi-release scenario). If NPIs inexpensive enough, may even be useful after vaccines are available (e.g. see farmed animal infectious disease control). In theory can achieve disease control very efficiently using targeted NPIs []

In practice targeted NPIs have had difficulty with reliability
- multiple points of failure (gathering information, making good decisions with information, convincing people to modify behaviour in time to prevent transmissions)
- success rate at each step is not high enough (e.g. with 5 sequential steps that are each 50% effective, the overall effectiveness is 0.5^5 = 3.1%

During covid, several steps in the targeted NPIs used depended on selfless behaviour from individuals and sufficient attention from under-resourced public health. E.g. contact tracing where a limited number of PH employees convinced people to quarantine after exposure - potentially losing income and leisure during this time for no personal benefit. Surprising targeted NPIs worked as well as they did [] given how actively disincentivized they were. testament to fair amount of pro-social behaviour in time of crisis and hard work by public health (contact tracing etc.). However, in many places targeted NPIs were insufficient alone.


Without strong enough targeted NPIs, Infection rate rose to level where it had to be mediated by either infection-acquired immunity or substantially reduced socialization. This approach of reduced social contacts could be highly effective when supported by the population, but is extremely expensive (banning gatherings for everyone). In addition, broad NPIs were frequently only sufficiently supported when disease rate was relatively quite high (10e-3). This is the main mechanism for disease control that we would predict in a game-theory setting if actors were uncoordinated and self-serving.


Aim here is to strengthen low cost interventions so that neither infection or substantial social distancing occur (Like the Ebola response but for viruses with airborne and potentially pre-symptomatic transmission). Would be much more dependable if we can do so without relying on altruistic actions from individuals or heroic efforts from public health. Essentially, can we design a simple mechanism for coordinating (sufficiently) low-cost disease control within a self-serving population?



Will focus on strategies with as few steps as possible and where (in time of pandemic) it is both politically feasible and practically possible to mandate each step. Restricts what is possible though- seems like public support for mandating contact tracing apps is limited. Infeasible to mandate sharing recent contacts. Worthwhile where possible though - several countries demonstrated that mandating isolation for positive patients is possible and significantly increases effectiveness [AUS, China, Vietnam]. Mandating testing has been accepted in several contexts [].


In addition to mandating steps we propose to also incentivize them (both carrot and stick). There are several reasons for doing this:
	- even higher compliance
	-fairer: targeted interventions impose a significant burden on a small fraction of the population. Success positively impacts whole population so they deserve to be at least partially rewarded for it.
	-internalizes previously external costs (which disincentivizes unnecessary use of harmful public health policies like long quarantine or broad social distancing )
	-reliable over longer periods (avoid failure modes from Aus and China where lost public support)
	


# A proposed solution: incentivized and targeted frequent testing

Very simply, the strategy we will explore is to test many people often and isolate positives.

Meets design strategy: 
- has few steps: test, isolate positives
- both steps have strong evidence that mandates will be accepted and can be enforced [air travel, Bermuda, Australia]
- possible to incentivize (trivially with payments to fullly compensate for time, and potentially with more advanced schemes that we will return to later)

What we are poroposing here is not that different from what was implemented in many places (and that is a good thing - the goal is simple, sensible seeming strategy).

Mixed results in real world. explore problems and fix them. 
- insufficient frequency [Slovakia, Japan paper]. Interventions must be ongoing unless elimination achieved
- insufficient enforcement of isolation [US college]
- all disease control strategies are sensitive to importation rates. e.g. college community with frequent mixing with general population will see many importations, and this could mask effect of intervention. If possible, much better to reduce links with high prevalence populations (possible to do at country level with border control, or even province level [atlantic canada]).
- Overly unpleasant [china]. No financial incentives, isolated by force, also used centralized location tracking. Quite effective for a while, but even with level of government control eventually lost population support. With less support, less effective, and requires even more interventions, to point where protests and rampant spread. Aim to incentivize compliance, reduce friction, minimize data collection, and be less heavy-handed so that approach is palatable in more countries and could be sustained indefinitely. 


Useful to construct a very simplified mathematical model of the strategy to make explicit our assumptions and quantitively analyse points of failure. For simplicity, will only consider this strategy and not combinations of them. In a homogeneous population where fraction $\gamma$ test regularly, fraction $\sigma$ of counterfactual transmissions occur after receiving a positive test (depending on frequency, delay, and relationship between test sensitivity and infectiousness), and transmissions are reduced to fraction $\beta$ after receiving a positive test, the following equation gives the reproductive number.

$R_t = R_0 (1 - \gamma \sigma \beta)$

$\gamma$ depends on compliance and accessibility within the population. Ideally can increase by making very easy to get, paying people per test taken, and making it a pre-requisite for daily activities like going into school, work, stores



todo: compute fraction of transmissions after receiving positive test as function of frequency and delay for Covid



As described, expect to be sufficient for sustained low-cost control of almost completely asymptomatic R_0 = 2.5 virus, something that existing strategies cannot do. For more challenging scenarios (e.g. R_0 = 9, or substantial transmission capability on same day of negative test) it still provides a very strong starting point - reduce transmissions by large fraction, failure analysis of transmissions using phylo, norm setting for isolation, very high case detection (albeit delayed) to base contact tracing on. So could conceivably modify slightly and achieve control of dificult pathogens at similar cost (say with addition of immediate isolation of household members, increased testing frequency for contacts, and requirement to mask around strangers)

# Cost



```{r}
R0 = 3.0

computeCost = function(testFraction = 0.95, isoFraction = 0.9, testFreq = 0.5){
  transFraction = 0.8 # todo: make function of test frequency, delay, sensitivity, expected transmission function
  importRate = 1e-4
  
  
  testCost = 10 + 40
  isoCost = 10*(100 + 200) + 0.5*3000
  
  Rt = R0*(1 - testFraction*transFraction*isoFraction)
  
  dailyCostPerPerson = testFraction*testFreq*testCost + importRate*1/(1-Rt)*testFraction*isoCost
  gdpPerCapita = 70e3 # gdp per person in USA
  return(dailyCostPerPerson*365/gdpPerCapita)
}
```






# Notes:


Two scenarios:

1. Pandemic, where there is ability to close borders to high prevalence countries (and ideally keep them open to low prev). Model as 1/100 flow between high prev- leading to below 1/10000 import rate relative to normal flow

2. Business as usual, where border restrictions not possible

First is easier because import rate much lower and because willingness to spend to prevent infections is higher. It is also higher stakes and currently unsolved, so will focus on that in this manuscript. 




Dependent on border restrictions, so aim for cost less than that

Two questions- will it work and is it better than alternatives. Both disease dependent, but for 




